import { Inter } from 'next/font/google';
import './globals.css';
import { NavbarSection } from '@/components/NavbarSection';
import { Footer } from '@/components/Footer';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';
import { CookiesProvider } from 'next-client-cookies/server';
import SessionProvider from '@/provider/SessionProvider';
import QueryProvider from '@/provider/QueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Ticketing App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'antialiased min-h-screen')}>
        <CookiesProvider>
          <QueryProvider>
            <SessionProvider>
              <NavbarSection />
              {children}
              <Toaster />
              <Footer />
            </SessionProvider>
          </QueryProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
