import { Inter } from 'next/font/google';
import './globals.css';
import { NavbarSection } from '@/components/NavbarSection';
import { Footer } from '@/components/Footer';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';
import Provider from '@/components/provider/Provider';
import { CookiesProvider } from 'next-client-cookies/server';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'antialiased min-h-screen')}>
        <Provider>
          <CookiesProvider>
            <NavbarSection />
            {children}
            <Toaster />
            <Footer />
          </CookiesProvider>
        </Provider>
      </body>
    </html>
  );
}
