import { Inter } from 'next/font/google';
import './globals.css';
import { NavbarSection } from '@/components/NavbarSection';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarSection />
        {children}
      </body>
    </html>
  );
}
